digitalocean/do-markdownit

CHANGELOG.md
script/prism.js

- **PrismJS Integration:** Vendoring
N/A
Relies on `require.resolve` to locate the directory that PrismJS is in, rather than a hardcoded constant.
Package can be installed.

Use require.resolve to locate Prism for patching

---

CHANGELOG.md
rules/user_mention.js
rules/user_mention.test.js

- **Markdown-It Plugins:** user_mention
DODX-5308
Bug fix for the user mentions plugin logic, stopping it from injecting mentions within an existing link, which was previously caused invalid HTML and broken links to be generated.
When a mention is used within an existing markdown link, the mention will be ignored and left as the existing link.

Do not inject mentions when inside a link

---

CHANGELOG.md
modifiers/prismjs.test.js
util/dom_utils.js
util/prism_keep_html.js

- **PrismJS Integration:** prism_keep_html plugin
DODX-5226
Fixes an issue observed when a highlight ended inside a multi-line token, where the split in the HTML preservation would be off by one token, resulting in incorrect preservation of the HTML.
I'm not 100% happy with this fix in that I'm not sure I've really found the root cause, but I could see that the issue was indeed that the splitting was off by one character when doing the closing split for HTML preservation, or rather, the closing node that was split on ended up in the wrong side of the tree.
The change in this PR fixes that edge case, and does not break any other tests relating to highlighting or HTML preservation, so I'm confident this doesn't appear to make things worse.
This PR includes a change to the signature of …

Fix issue with HTML preservation inside a multi-line token

---

CHANGELOG.md
README.md
fixtures/full-input.md
fixtures/full-output.html
index.js
rules/embeds/caniuse.js
rules/embeds/caniuse.test.js

- **Markdown-It Plugins:** embeds/caniuse
N/A
Introduces a new block that allows for a feature from CanIUse.com to be embedded into the Markdown content.
(This also moves terminal_button up to be loaded immediately after rsvp_button, before many of the other embeds, for more logical grouping in the source)
All customisation flags supported by the embed provider are supported in the Markdown syntax correctly. Using the new Markdown syntax results in embeds correctly rendering as you'd expect them to.

CanIUse embeds

---

.eslintrc.js
.gitignore
.npmignore
CHANGELOG.md
dev/client.html
dev/client.js
dev/render.js
dev/webpack.config.js
index.test.js
package-lock.json
package.json

- **Something else:** Development setup
N/A
Introduces a new development setup using Webpack for the plugin, that provides a webpage with hot-reloading for the plugins, and a real-time text box for testing the Markdown rendering.
Running `npm run dev` will start up a Webpack dev server which provides a single webpage with a textbox for Markdown content, rendering every change to an HTML preview in a side-by-side layout (wrapped on mobile).

Add development setup using Webpack

---

CHANGELOG.md
README.md
dev/client.js
fixtures/full-output.html
index.js
rules/embeds/caniuse.js
rules/embeds/codepen.js
rules/embeds/dns.js
rules/embeds/glob.js
rules/image_caption.js
rules/image_caption.test.js
styles/_images.scss

- **Markdown-It Plugins:** New image_caption plugin
- **SCSS Styling:** Image styles
- **Something else:** Dev script
N/A
Introduces a new plugin that will wrap singleton images (images that are the only element in a paragraph) that have a title in a figure with a figcaption set to be the title (rendered as inline Markdown).
This also includes a couple of tweaks to the dev script to better handle the re-rendering of the content, ensuring embed scripts re-run correctly.
An image on its own that has a title set will be rendered as a figure with a figcaption matching the title.
An image that has other text surrounding it will not be wrapped in a figure, even if it has a title.
An image without a title set will never be rendered as a figure.

Render captions for singleton images with titles

---

CHANGELOG.md
README.md
fixtures/full-input.md
fixtures/full-output.html
index.js
rules/embeds/callout.js
rules/embeds/columns.js
rules/embeds/details.js
rules/embeds/details.test.js
rules/embeds/glob.js
rules/html_comment.js
styles/_details.scss
styles/index.scss
util/block_lines.js
util/find_block_embed.js

- **Markdown-It Plugins:** Details embed
- **SCSS Styling:** Details
N/A
Introduces new syntax similar to columns that allows for HTML `<details>` to be generated. Includes some abstraction of duplicated logic within the plugins. Text on the opening line of the details syntax is treated as inline Markdown for the summary, and content inside the details block is treated as block Markdown for the hidden details content.
The following syntax can be used to create details blocks that are styled and natively interactive in browsers:
```md
[details This is a details section
This is hidden content
> This is block content inside
]
```

Add syntax for expandable details

---

CHANGELOG.md
rules/embeds/details.test.js
util/find_block_embed.js

- **Something else:** Block detection util (for details + columns)
N/A
Fixes the detection of embed blocks when a line inside the block started with `[` that was closed with a `]` inside the same line (not at the end of the line).
A details block or a column that contains a link inside the block should render correctly, not as plain text.
```md
[details Test
[a link](/test)
]
```

Fix block detection with links at start of line

---

CHANGELOG.md
README.md
modifiers/heading_id.js
modifiers/heading_id.test.js

- **Markdown-It Plugins:** heading_id
N/A
Exposes the level for each heading in the `headings` object generated by `heading_id`.
`level` property is present in each object within `headings` when the `heading_id` plugin is used.

Expose heading levels in heading_id

---

CHANGELOG.md
dev/client.scss
styles/_typography.scss

- **SCSS Styling:** Root styles
N/A
Fixes the styling of inline code within links (as we set a negative z-index on the inline code to render it beneath the link underline) by ensuring that the root of the Markdown container has a z-index of 0 (so that it doesn't also render beneath the root/parents if there was a background set).
Inline code within links is visible, with the code rendering beneath the underline:
```md
[`test`]()
```

Fix styling of inline code within a link

---

CHANGELOG.md
styles/_typography.scss

- **SCSS Styling:** Root styles
cc #31 
Follow on to #31, and part of the same issue. For usages that aren't in a grid context `position: relative` is required to allow the `z-index` to actually apply.
`position: relative` is set in root styling, alongside the `z-index`.

Set position relative on root styles for z-index

---

CHANGELOG.md
script/prism.js

- **PrismJS Integration:** Build script
N/A
Removes the minified versions of Prism components/plugins during the patch process. This reduces the resulting bundle size when using the plugin with a bundler like Webpack, as the dynamic import in the Prism plugin resolves to less potential files.
When package is installed, the resulting vendored version of Prism does not contain minified JavaScript components or plugins.

Remove minified versions of patched Prism files

---

CHANGELOG.md
README.md
dev/client.scss
fixtures/full-output.html
rules/embeds/wistia.js
rules/embeds/wistia.test.js
rules/embeds/youtube.js
rules/embeds/youtube.test.js
styles/_details.scss
styles/_typography.scss
styles/_wistia.scss
styles/_youtube.scss
util/reduce_fraction.js

- **Markdown-It Plugins:** YouTube, Wistia
- **SCSS Styling:** YouTube, Wistia, Details, Lists
- **Something else:** Dev setup
N/A
Fixes assorted minor responsiveness issues within the plugin and its styling.
Sets an aspect-ratio value on YouTube/Wistia embeds alongside a max-width of 100%, ensuring they don't overflow the container and resize to fit while maintaining the original aspect ratio.
Tweaks the behaviour of ordered and unordered lists to render the bullets inside the container below the tablet breakpoint, instead of outside the container.
Tweaks the summary section of details to ensure that long titles don't overlap the caret indicator.
Tweaks the dev setup to ensure an overflow doesn't happen when the viewport is below the grid min width (384px).
When on a small mobile device …

Set aspect-ratio on YouTube/Wistia, responsiveness fixes

---

CHANGELOG.md
README.md
fixtures/full-input.md
fixtures/full-output.html
index.js
modifiers/underline.js
modifiers/underline.test.js

- **Markdown-It Plugins:** Underline modifier
N/A
Adds a new modifier which wraps the standard rendering for bold text, switching the output HTML to be underlined when the syntax used is `__`.
Using `__` for text allows it to be underlined. Combining `__` and `**` allows text to be both bold and underlined.

Add modifier to enable underline syntax

---

CHANGELOG.md
fixtures/full-input.md
fixtures/full-output.html

- **Something else:** Markdown demo content
N/A
We've observed that the number of embeds in the demo content tends to cause a lot of browser lag. This PR reduces the embed count by removing embed variations for demonstrating flags, instead preferring to list the flags without live examples.
One embed exists per embed type still, with supported flags being listed after the embed.

Reduce embed count in demo content, list supported flags

---

CHANGELOG.md
README.md
dev/render.js
fixtures/full-output.html
modifiers/heading_id.js
modifiers/heading_id.test.js
styles/_heading_id.scss
styles/index.scss

- **Markdown-It Plugins:** heading_id - add hash link option
n/a
Add an option to add hash links next to headings 1-3
Turning on option in plugin will generate an anchor next to the heading and clicking it will scroll the page to that section

Add hash links to headings in heading_id plugin

---

CHANGELOG.md
README.md
fixtures/full-input.md
fixtures/full-output.html
index.js
rules/embeds/vimeo.js
rules/embeds/vimeo.test.js
styles/_vimeo.scss
styles/index.scss

- **Markdown-It Plugins:**  Vimeo
N/A
This introduces a new plugin with syntax for embedding videos from Vimeo in Markdown. The syntax is [vimeo <URL>], following the same pattern as many of our other embed plugins.
Like other embed plugins, it also supports optional flags after the URL, in this case for setting the width and/or height of the embed (default values are for height 270px and for width 480px).
The new syntax works as expected, allowing the user to embed videos from Vimeo in Markdown content, optionally setting a custom width and/or height.

Add vimeo embed

---

CHANGELOG.md
README.md
fixtures/full-input.md
fixtures/full-output.html
index.js
rules/embeds/instagram.js
rules/embeds/instagram.test.js
styles/_instagram.scss
styles/index.scss

- **Markdown-It Plugins:** Instagram
N/A
This introduces a new plugin with syntax for embedding posts from Instagram in Markdown. The syntax is [instagram <URL>], following the same pattern as many of our other embed plugins.
Like other embed plugins, it also supports optional flags after the URL, in this case for setting the alignment (left/center/right), and the width (between 326 and 550, per Instagram's docs).
The new syntax works as expected, allowing the user to embed Instagram posts in Markdown content, optionally changing the post alignment or setting a custom width for the post.

Add Instagram plugin

---

CHANGELOG.md
README.md
fixtures/full-input.md
fixtures/full-output.html
index.js
rules/embeds/slideshow.js
rules/embeds/slideshow.test.js
styles/_slideshow.scss
styles/index.scss

- **Markdown-It Plugins:** Slideshow plugin
N/A
This introduces a new plugin with syntax for embedding slideshows in Markdown. The syntax is [slideshow <url1> <url2> ... <url<n>> ], following the same pattern as many of our other embed plugins.
Like other embed plugins, it also supports optional flags after the URLs, in this case for setting the height and/or the width (default value is 270px for height and 480px for width ).
The new syntax works as expected, allowing the user to embed slideshows in Markdown content, optionally changing the height and/or width for the images.

Add slideshow plugin

---

CHANGELOG.md
fixtures/full-output.html
modifiers/heading_id.js
modifiers/heading_id.test.js
styles/_heading_id.scss
styles/_typography.scss

- **Markdown-It Plugins:** Heading id (hash links)
- **SCSS Styling:** Typography (headings), heading id (hash links)
N/A
Implements a few new settings for the hash links feature of the heading id plugin:
- Allows the position of the hash link to be changed to after the heading text (defaults to before to be non-breaking)
- Makes the heading text itself also a link to the hash link (can be disabled via a setting)
- Makes both the hash link itself and the heading text link write the link to clipboard when clicked (can be disabled via a setting)
Hash links continue to render before the heading by default, but now write the link to your clipboard when clicked, and the whole heading is clickable.
Tests cover all variations of the settings and have the correct expected outputs.

Hash link position, heading link + clipboard settings

---

CHANGELOG.md
README.md

- **Something else:** Docs
N/A
Fixes the ordering/levels of the headings in the README so that the limit_tokens plugin information is a sub-heading of the plugins, rather than being an isolated top-level heading further down the document.
Fixes the listed options for the heading_id plugin, as I forgot in #64 that the nested options for hash links are also included in the README.
limit_tokens heading is correctly nested under the plugins list in the README.
heading_id hash link options are correctly listed in the README.

Fix README heading ordering, add missing heading_id opts

---

CHANGELOG.md
fixtures/full-output.html
modifiers/heading_id.js
modifiers/heading_id.test.js

- **Markdown-It Plugins:** heading_id
cc #64 
I had this stashed locally for #64 but never commited/pushed it -- the current functionality was meant to use `this.getAttribute('href')` as part of manually composing the URL, but was then partially switched to using `this.href` resulting in the URL being duplicated.
This PR fixes that functionality to fully switch to just using `this.href`, which contains the fully composed/parsed URL for the anchor already.
Clicking on a heading copies the correct URL to your clipboard.

Fix clipboard write in heading_id hash links

---

CHANGELOG.md
README.md
modifiers/prismjs.js
util/prism_util.js

- **PrismJS Integration:** Webpack, language resolution
N/A
Updates the dependency resolution logic when loading languages for PrismJS.
Exposes a new method to instantiate Webpack's Context Replacement plugin, allowing the languages included for PrismJS in Webpack bundles to be restricted.
Prism continues to load languages as expected, rendering code blocks.
Webpack plugin can be used to correctly restrict the bundling of Prism languages to the requested languages and their dependencies.

Add util to restrict Prism bundle in Webpack

---

CHANGELOG.md
README.md
modifiers/image_settings.js
util/helpers.js
util/prism_util.js
util/prism_webpack.js

- **PrismJS Integration:** Webpack
cc #69 
Isolates the logic introduced in #69 to handle the case where a bundle is unable to tree-shake dead code paths, and so attempts to bundle Webpack itself.
Webpack-related logic for Prism is in an isolated file not imported by plugins.

Isolate Prism webpack logic in own file

---

.gitignore
.npmignore
CHANGELOG.md
package-lock.json
package.json

- **Build Scripts:** Typings
N/A
Introduces TypeScript as a dev dependency, so that prior to publishing a new release we can generate typings from the JSDoc comments automatically.
This also introduced a changelog entry for #77 + #78, and fixes the changelog headings that I did incorrectly in #73 + #76.
Running `npm publish --dry-run` locally results in the `types` directory being created, and the files within `types` being listed in the NPM output, excluding the files in `types/vendor`.

Generate TypeScript definitions for package

---

dev/client.js

- **Something else:** Dev playground
N/A
Enables Prism in the dev playground (`npm run dev`), so that the code-block toolbar etc. can be tested fully.
_No changelog entry as this is a dev-only change._
Code blocks continue to render as expected in the dev playground.

Enable client-side Prism in dev playground

---

CHANGELOG.md
styles/_callouts.scss
styles/_code.scss
styles/_code_label.scss
styles/_code_prism.scss
styles/_code_secondary_label.scss
styles/_highlight.scss
styles/_mixins.scss
styles/_theme.scss
styles/_typography.scss
styles/digitalocean/_callouts.scss
styles/digitalocean/_code_environments.scss

- **SCSS Styling:** 
- Prism environment code blocks themes
Update color themes for code blocks
Updates color themes for code blocks
Color themes for the code blocks are updated to use new color scheme

Update color palette to match new design system

---

CHANGELOG.md
package-lock.json
package.json

- **Something else:** Dependencies
N/A
Updates the development version of markdown-it to the latest release 14.0.0.
Also, marks markdown-it as a peer dependency of the package, as the plugin is intended to be used with it.
Tests all pass, dev environment works as expected still.

Update markdown-it to 14.0.0

---

CHANGELOG.md
rules/embeds/glob.js
rules/embeds/glob.test.js

- **Markdown-It Plugins:** Glob embed
N/A
The previous implementation of the regex pattern used for the glob embed could result in too much recursion when evaluating a string that had a large number of spaces in the glob, followed by a test on a new line.
This PR restricts the regex pattern being used, so instead of looking for a space followed by _any_ character, we're now looking for a space followed by _any non-space_ character, avoiding the excessive recursion. A test has also been added to confirm that this regex no longer has this ReDoS issue.
All tests continue to pass, including the new one that would previously reproduce the ReDoS.

Restrict pattern for space-separated arguments in glob embed regex

---

CHANGELOG.md
rules/embeds/glob.js
rules/embeds/glob.test.js

- **Markdown-It Plugins:** Glob embed
Relates to #92
`URL#searchParams#append` seems to have terrible performance when working with a large number of parameters, across different runtimes and browsers: https://twitter.com/MattIPv4/status/1748102513646047584 (https://twitter.com/MattIPv4/status/1748116227703099900)
While it is unlikely in regular use that the glob embed would encounter enough tests being provided for this to actually be an issue, it was reported as a potential attack vector in the library.
As such, this PR switches us over to a more old-fashioned approach of using `encodeURIComponent` in a loop, which shouldn't risk any drastic performance issues in such an edge case.
This also includes a minor refactor of the glob regex that was fixed in #92 so it is easier to follow what …

Avoid slowdown from `URL#searchParams` in glob embed

---

CHANGELOG.md
PUBLISH.md

- **Something else:** Docs
N/A
As I was prepping the 1.12.3 release, I noticed that the documentation around creating a release was outdated, so this updates it to have more accurate instructions.
Docs make sense.

Update PUBLISH + CHANGELOG instructions for new versions

---

CHANGELOG.md
fixtures/full-input.md
fixtures/full-output.html
styles/_code.scss
styles/_code_prism.scss
styles/_typography.scss

- **SCSS Styling:** Code/links
N/A
Fix the styling of inline code that is within a link, so that the text in the inline code is visible while the link is being hovered. To allow for the code background and the link background to layer properly alongside the code text, I switched the background on inline code elements to being a pseudo-element, so I can layer it behind the background of the link.
Also, while I was here, I tweaked the alignment of the copy button in code blocks using Prism, as it looked rather off-center vertically in code blocks that had a single line of code.
Links on their own continue to look visually correct.
Inline code on its own continues to look visually correct.
Inline code with a variable inside continues to look visually correct.
Links with inline code inside …

Fix inline code styling when in a link

---

CHANGELOG.md
styles/_code.scss
styles/_typography.scss

- **SCSS Styling:** Code/links
cc #103
While #103 did fix the more prevalent issue of inline code in links becoming unreadable when hovered, that fix ended up breaking the less common situation of inline code spanning across a linebreak (due to the background now being a pseudo-element rather than an actual background).
To fix this, I've partially reverted the change the previous PR made, sticking to using just a regular old background for inline code, and have then changed how inline code inside a link gets styled to use multiple background layers to combine the link treatment with the inline code background seamlessly.
- Inline code, including across linebreaks, has a background
- Inline code, inside a link, including across linebreaks, has a background
- Regular text, inside a link, …

Fix multi-line inline code styling

---

CHANGELOG.md
README.md
index.js
modifiers/link_attributes.js
modifiers/link_attributes.test.js

- **Markdown-It Plugins:** Link attributes
N/A
Allows for custom attributes to be set on all links generated by the Markdown. For example, this would allow for `href`s to be transformed if required, or to modify the `rel` for links in user-generated content.
Test cases cover expected usage. Documentation is correct.

Add plugin to set attributes on links

---

package.json

- **Something else:** Release tooling
N/A
Disables type checking for dependencies, as there appears to be type issues within `@types/eslint-scope`.
```
node_modules/@types/eslint-scope/index.d.ts:12:5 - error TS2416: Property 'scopes' in type 'ScopeManager' is not assignable to the same property in base type 'ScopeManager'.
Type 'import("[snip]/do-markdownit/node_modules/@types/eslint-scope/index").Scope[]' is not assignable to type 'import("[snip]/do-markdownit/node_modules/@types/eslint/index").Scope.Scope[]'.
Type 'import("[snip]/do-markdownit/node_modules/@types/eslint-scope/index").Scope' is not assignable to type 'import("[snip]/do-markdownit/node_modules/@types/eslint/index").Scope.Scope'.
Types of property 'variables' are incompatible.
Type …
```

Set --skipLibCheck for tsc

---

CHANGELOG.md
README.md
fixtures/full-output.html
index.js
rules/collapsible_heading.js
rules/collapsible_heading.test.js

- **Markdown-It Plugins:** Make Collapsible Heading plugin not enabled by default
By having the Collapsible Heading plugin enabled by default it transforms headings in unexpected places.
Collapsible Heading plugin should only transform specific headings on the desired usages.
Collapsible Heading plugin is not transforming any headings by default. When configured it transforms the configured headings as expected.

Make Collapsible Heading plugin not enabled by default
