- .editorconfig
- .github/workflows/ci.yml
- CHANGELOG.md
- jest.config.js
- **Something else:** GitHub Actions
N/A
Adds GitHub Actions workflow for CI, running linting and testing for the package on every PR & pushed commit.
Two Actions jobs should show, CI/Test and CI/Lint, and both should pass.
> Add actions for testing & linting

- CHANGELOG.md
- package-lock.json
- package.json
- **Something else:** Dependency updates
N/A
Updates all dependencies to their latest versions, and resolves a dependency vulnerability. No user-facing impact.
Dependencies are updated, plugin continues to function with these updates applied. Tests and lining continue to pass.
> Dependency updates

- .gitignore
- .npmignore
- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.0.3
(Also fixes a few generated directories in the ignore configs)
Version updated to 1.0.3, changelog updated. jsdoc & coverage generated files ignored.
> Release v1.0.3

- .eslintrc.js
- CHANGELOG.md
- README.md
- fixtures/full-input.md
- fixtures/full-output.html
- index.js
- rules/embeds/asciinema.test.js
- rules/embeds/codepen.js
- rules/embeds/codepen.test.js
- rules/embeds/dns.test.js
- rules/embeds/glitch.js
- rules/embeds/glitch.test.js
- rules/embeds/glob.test.js
- rules/embeds/rsvp_button.test.js
- rules/embeds/terminal_button.test.js
- rules/embeds/youtube.test.js
- **Markdown-It Plugins:** Glitch
N/A
Implements a new embed plugin to support Glitch projects. Also refines testing across other embeds, and the full test Markdown.
Introduces new Markdown block syntax that allows for Glitch projects to be embedded, supporting all customisations that Glitch allows for embeds.
> Glitch embeds

- CHANGELOG.md
- README.md
- fixtures/full-input.md
- fixtures/full-output.html
- index.js
- rules/embeds/wistia.js
- rules/embeds/wistia.test.js
- rules/embeds/youtube.js
- styles/_wistia.scss
- **Build Scripts:** Add testing for Wistia embeds.
- **Markdown-It Plugins:** Add support for Wistia embeds.
- **SCSS Styling:** Add styling for Wistia embeds.
N/A
Adds Wistia Embed support.
Wistia embed should properly appear on the index markdown page when running the project. All tests should pass.
> Add Wistia Embeds

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.3.1
Version updated to 1.3.1, changelog updated.
> Release v1.3.1

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.3.2
Version updated to 1.3.2, changelog updated.
> Release v1.3.2

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.3.3
Version updated to 1.3.3, changelog updated.
> Release v1.3.3

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.5.0
Version updated to 1.5.0, changelog updated.
> Release v1.5.0

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.5.1
Version updated to 1.5.1, changelog updated.
> Release v1.5.1

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.6.0
Version updated to 1.6.0, changelog updated.
> Release v1.6.0

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.6.1
Version updated to 1.6.1, changelog updated.
> Release v1.6.1

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.7.0
Version updated to 1.7.0, changelog updated.
> Release v1.7.0

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.8.0
Version updated to 1.8.0, changelog updated.
> Release v1.8.0

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.9.0
Version updated to 1.9.0, changelog updated.
> Release v1.9.0

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.11.0
Version updated to 1.11.0, changelog updated.
> Release v1.11.0

- CHANGELOG.md
- styles/_code.scss
- **SCSS Styling:**  Added border to code block
Add a 2px inner shadow to the code blocks
Code blocks should have a 2px inner shadow
> Add border stroke to code block

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.12.0
Version updated to 1.12.0, changelog updated.
> Release v1.12.0

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.12.1
Version updated to 1.12.1, changelog updated.
> Release v1.12.1

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.12.2
Version updated to 1.12.2, changelog updated.
> Release v1.12.2

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.12.3
Version updated to 1.12.3, changelog updated.
> Release v1.12.3

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.12.4
Version updated to 1.12.4, changelog updated.
> Release v1.12.4

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.12.5
Version updated to 1.12.5, changelog updated.
> Release v1.12.5

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.12.6
Version updated to 1.12.6, changelog updated.
> Release v1.12.6

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.13.0
Version updated to 1.13.0, changelog updated.
> Release v1.13.0

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.14.0
Version updated to 1.14.0, changelog updated.
> Release v1.14.0

- CHANGELOG.md
- package-lock.json
- package.json
- **Something else:** New minor release.
Adding collapsible headings plugin
Cuts a new minor release for the collapsible headings plugin
New release is available for external consumption.
> Release v1.15.0

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.16.0
Version updated to 1.16.0, changelog updated.
> Release v1.16.0

- CHANGELOG.md
- package-lock.json
- package.json
N/A
Release v1.16.1
Version updated to 1.16.1, changelog updated.
> Release v1.16.1
